// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/kvstore.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_kvstore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kvstore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_kvstore_proto_rawDescGZIP(), []int{0}
}

type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_proto_kvstore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kvstore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_proto_kvstore_proto_rawDescGZIP(), []int{1}
}

func (x *PutRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PutRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`                                        // true = committed at primary + both backups
	RedirectAddr  string                 `protobuf:"bytes,2,opt,name=redirect_addr,json=redirectAddr,proto3" json:"redirect_addr,omitempty"` // non-empty when ok=false and caller hit a non-primary
	LamportTs     int64                  `protobuf:"varint,3,opt,name=lamport_ts,json=lamportTs,proto3" json:"lamport_ts,omitempty"`         // Lamport timestamp assigned to this write (when ok=true)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_proto_kvstore_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kvstore_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_proto_kvstore_proto_rawDescGZIP(), []int{2}
}

func (x *PutResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *PutResponse) GetRedirectAddr() string {
	if x != nil {
		return x.RedirectAddr
	}
	return ""
}

func (x *PutResponse) GetLamportTs() int64 {
	if x != nil {
		return x.LamportTs
	}
	return 0
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_proto_kvstore_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kvstore_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_kvstore_proto_rawDescGZIP(), []int{3}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	LamportTs     int64                  `protobuf:"varint,3,opt,name=lamport_ts,json=lamportTs,proto3" json:"lamport_ts,omitempty"` // Lamport timestamp of the write that produced this value
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_proto_kvstore_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kvstore_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_proto_kvstore_proto_rawDescGZIP(), []int{4}
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *GetResponse) GetLamportTs() int64 {
	if x != nil {
		return x.LamportTs
	}
	return 0
}

type GetPrimaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrimaryAddr   string                 `protobuf:"bytes,1,opt,name=primary_addr,json=primaryAddr,proto3" json:"primary_addr,omitempty"` // client-facing address of the current primary
	PrimaryId     int32                  `protobuf:"varint,2,opt,name=primary_id,json=primaryId,proto3" json:"primary_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPrimaryResponse) Reset() {
	*x = GetPrimaryResponse{}
	mi := &file_proto_kvstore_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPrimaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPrimaryResponse) ProtoMessage() {}

func (x *GetPrimaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kvstore_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPrimaryResponse.ProtoReflect.Descriptor instead.
func (*GetPrimaryResponse) Descriptor() ([]byte, []int) {
	return file_proto_kvstore_proto_rawDescGZIP(), []int{5}
}

func (x *GetPrimaryResponse) GetPrimaryAddr() string {
	if x != nil {
		return x.PrimaryAddr
	}
	return ""
}

func (x *GetPrimaryResponse) GetPrimaryId() int32 {
	if x != nil {
		return x.PrimaryId
	}
	return 0
}

type ReplicateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	LamportTs     int64                  `protobuf:"varint,3,opt,name=lamport_ts,json=lamportTs,proto3" json:"lamport_ts,omitempty"` // timestamp assigned by the primary (apply max-rule)
	OriginId      int32                  `protobuf:"varint,4,opt,name=origin_id,json=originId,proto3" json:"origin_id,omitempty"`    // ID of the node acting as primary
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicateRequest) Reset() {
	*x = ReplicateRequest{}
	mi := &file_proto_kvstore_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateRequest) ProtoMessage() {}

func (x *ReplicateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kvstore_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateRequest.ProtoReflect.Descriptor instead.
func (*ReplicateRequest) Descriptor() ([]byte, []int) {
	return file_proto_kvstore_proto_rawDescGZIP(), []int{6}
}

func (x *ReplicateRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ReplicateRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ReplicateRequest) GetLamportTs() int64 {
	if x != nil {
		return x.LamportTs
	}
	return 0
}

func (x *ReplicateRequest) GetOriginId() int32 {
	if x != nil {
		return x.OriginId
	}
	return 0
}

type ReplicateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	LamportTs     int64                  `protobuf:"varint,2,opt,name=lamport_ts,json=lamportTs,proto3" json:"lamport_ts,omitempty"` // backup's Lamport clock after applying the max-rule
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicateResponse) Reset() {
	*x = ReplicateResponse{}
	mi := &file_proto_kvstore_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateResponse) ProtoMessage() {}

func (x *ReplicateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kvstore_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateResponse.ProtoReflect.Descriptor instead.
func (*ReplicateResponse) Descriptor() ([]byte, []int) {
	return file_proto_kvstore_proto_rawDescGZIP(), []int{7}
}

func (x *ReplicateResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ReplicateResponse) GetLamportTs() int64 {
	if x != nil {
		return x.LamportTs
	}
	return 0
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      int32                  `protobuf:"varint,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	LamportTs     int64                  `protobuf:"varint,2,opt,name=lamport_ts,json=lamportTs,proto3" json:"lamport_ts,omitempty"`
	Role          int32                  `protobuf:"varint,3,opt,name=role,proto3" json:"role,omitempty"` // 0 = PRIMARY, 1 = BACKUP, 2 = CANDIDATE
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_kvstore_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kvstore_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_kvstore_proto_rawDescGZIP(), []int{8}
}

func (x *HeartbeatRequest) GetSenderId() int32 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *HeartbeatRequest) GetLamportTs() int64 {
	if x != nil {
		return x.LamportTs
	}
	return 0
}

func (x *HeartbeatRequest) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      int32                  `protobuf:"varint,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	LamportTs     int64                  `protobuf:"varint,2,opt,name=lamport_ts,json=lamportTs,proto3" json:"lamport_ts,omitempty"`
	Role          int32                  `protobuf:"varint,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_kvstore_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kvstore_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_kvstore_proto_rawDescGZIP(), []int{9}
}

func (x *HeartbeatResponse) GetSenderId() int32 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *HeartbeatResponse) GetLamportTs() int64 {
	if x != nil {
		return x.LamportTs
	}
	return 0
}

func (x *HeartbeatResponse) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

type AnnounceLeaderRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NewPrimaryId    int32                  `protobuf:"varint,1,opt,name=new_primary_id,json=newPrimaryId,proto3" json:"new_primary_id,omitempty"`
	ElectionLamport int64                  `protobuf:"varint,2,opt,name=election_lamport,json=electionLamport,proto3" json:"election_lamport,omitempty"` // candidate's Lamport clock at election time
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AnnounceLeaderRequest) Reset() {
	*x = AnnounceLeaderRequest{}
	mi := &file_proto_kvstore_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnnounceLeaderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnounceLeaderRequest) ProtoMessage() {}

func (x *AnnounceLeaderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kvstore_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnounceLeaderRequest.ProtoReflect.Descriptor instead.
func (*AnnounceLeaderRequest) Descriptor() ([]byte, []int) {
	return file_proto_kvstore_proto_rawDescGZIP(), []int{10}
}

func (x *AnnounceLeaderRequest) GetNewPrimaryId() int32 {
	if x != nil {
		return x.NewPrimaryId
	}
	return 0
}

func (x *AnnounceLeaderRequest) GetElectionLamport() int64 {
	if x != nil {
		return x.ElectionLamport
	}
	return 0
}

type AnnounceLeaderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"` // true if the recipient yields to this candidate
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnnounceLeaderResponse) Reset() {
	*x = AnnounceLeaderResponse{}
	mi := &file_proto_kvstore_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnnounceLeaderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnounceLeaderResponse) ProtoMessage() {}

func (x *AnnounceLeaderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kvstore_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnounceLeaderResponse.ProtoReflect.Descriptor instead.
func (*AnnounceLeaderResponse) Descriptor() ([]byte, []int) {
	return file_proto_kvstore_proto_rawDescGZIP(), []int{11}
}

func (x *AnnounceLeaderResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

var File_proto_kvstore_proto protoreflect.FileDescriptor

const file_proto_kvstore_proto_rawDesc = "" +
	"\n" +
	"\x13proto/kvstore.proto\x12\akvstore\"\a\n" +
	"\x05Empty\"4\n" +
	"\n" +
	"PutRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"a\n" +
	"\vPutResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12#\n" +
	"\rredirect_addr\x18\x02 \x01(\tR\fredirectAddr\x12\x1d\n" +
	"\n" +
	"lamport_ts\x18\x03 \x01(\x03R\tlamportTs\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"X\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x1d\n" +
	"\n" +
	"lamport_ts\x18\x03 \x01(\x03R\tlamportTs\"V\n" +
	"\x12GetPrimaryResponse\x12!\n" +
	"\fprimary_addr\x18\x01 \x01(\tR\vprimaryAddr\x12\x1d\n" +
	"\n" +
	"primary_id\x18\x02 \x01(\x05R\tprimaryId\"v\n" +
	"\x10ReplicateRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x1d\n" +
	"\n" +
	"lamport_ts\x18\x03 \x01(\x03R\tlamportTs\x12\x1b\n" +
	"\torigin_id\x18\x04 \x01(\x05R\boriginId\"B\n" +
	"\x11ReplicateResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1d\n" +
	"\n" +
	"lamport_ts\x18\x02 \x01(\x03R\tlamportTs\"b\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\x05R\bsenderId\x12\x1d\n" +
	"\n" +
	"lamport_ts\x18\x02 \x01(\x03R\tlamportTs\x12\x12\n" +
	"\x04role\x18\x03 \x01(\x05R\x04role\"c\n" +
	"\x11HeartbeatResponse\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\x05R\bsenderId\x12\x1d\n" +
	"\n" +
	"lamport_ts\x18\x02 \x01(\x03R\tlamportTs\x12\x12\n" +
	"\x04role\x18\x03 \x01(\x05R\x04role\"h\n" +
	"\x15AnnounceLeaderRequest\x12$\n" +
	"\x0enew_primary_id\x18\x01 \x01(\x05R\fnewPrimaryId\x12)\n" +
	"\x10election_lamport\x18\x02 \x01(\x03R\x0felectionLamport\"4\n" +
	"\x16AnnounceLeaderResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted2\xa8\x01\n" +
	"\aKVStore\x120\n" +
	"\x03Put\x12\x13.kvstore.PutRequest\x1a\x14.kvstore.PutResponse\x120\n" +
	"\x03Get\x12\x13.kvstore.GetRequest\x1a\x14.kvstore.GetResponse\x129\n" +
	"\n" +
	"GetPrimary\x12\x0e.kvstore.Empty\x1a\x1b.kvstore.GetPrimaryResponse2\xe8\x01\n" +
	"\vReplication\x12B\n" +
	"\tReplicate\x12\x19.kvstore.ReplicateRequest\x1a\x1a.kvstore.ReplicateResponse\x12B\n" +
	"\tHeartbeat\x12\x19.kvstore.HeartbeatRequest\x1a\x1a.kvstore.HeartbeatResponse\x12Q\n" +
	"\x0eAnnounceLeader\x12\x1e.kvstore.AnnounceLeaderRequest\x1a\x1f.kvstore.AnnounceLeaderResponseB\x0fZ\rkvstore/protob\x06proto3"

var (
	file_proto_kvstore_proto_rawDescOnce sync.Once
	file_proto_kvstore_proto_rawDescData []byte
)

func file_proto_kvstore_proto_rawDescGZIP() []byte {
	file_proto_kvstore_proto_rawDescOnce.Do(func() {
		file_proto_kvstore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_kvstore_proto_rawDesc), len(file_proto_kvstore_proto_rawDesc)))
	})
	return file_proto_kvstore_proto_rawDescData
}

var file_proto_kvstore_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_kvstore_proto_goTypes = []any{
	(*Empty)(nil),                  // 0: kvstore.Empty
	(*PutRequest)(nil),             // 1: kvstore.PutRequest
	(*PutResponse)(nil),            // 2: kvstore.PutResponse
	(*GetRequest)(nil),             // 3: kvstore.GetRequest
	(*GetResponse)(nil),            // 4: kvstore.GetResponse
	(*GetPrimaryResponse)(nil),     // 5: kvstore.GetPrimaryResponse
	(*ReplicateRequest)(nil),       // 6: kvstore.ReplicateRequest
	(*ReplicateResponse)(nil),      // 7: kvstore.ReplicateResponse
	(*HeartbeatRequest)(nil),       // 8: kvstore.HeartbeatRequest
	(*HeartbeatResponse)(nil),      // 9: kvstore.HeartbeatResponse
	(*AnnounceLeaderRequest)(nil),  // 10: kvstore.AnnounceLeaderRequest
	(*AnnounceLeaderResponse)(nil), // 11: kvstore.AnnounceLeaderResponse
}
var file_proto_kvstore_proto_depIdxs = []int32{
	1,  // 0: kvstore.KVStore.Put:input_type -> kvstore.PutRequest
	3,  // 1: kvstore.KVStore.Get:input_type -> kvstore.GetRequest
	0,  // 2: kvstore.KVStore.GetPrimary:input_type -> kvstore.Empty
	6,  // 3: kvstore.Replication.Replicate:input_type -> kvstore.ReplicateRequest
	8,  // 4: kvstore.Replication.Heartbeat:input_type -> kvstore.HeartbeatRequest
	10, // 5: kvstore.Replication.AnnounceLeader:input_type -> kvstore.AnnounceLeaderRequest
	2,  // 6: kvstore.KVStore.Put:output_type -> kvstore.PutResponse
	4,  // 7: kvstore.KVStore.Get:output_type -> kvstore.GetResponse
	5,  // 8: kvstore.KVStore.GetPrimary:output_type -> kvstore.GetPrimaryResponse
	7,  // 9: kvstore.Replication.Replicate:output_type -> kvstore.ReplicateResponse
	9,  // 10: kvstore.Replication.Heartbeat:output_type -> kvstore.HeartbeatResponse
	11, // 11: kvstore.Replication.AnnounceLeader:output_type -> kvstore.AnnounceLeaderResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_proto_kvstore_proto_init() }
func file_proto_kvstore_proto_init() {
	if File_proto_kvstore_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_kvstore_proto_rawDesc), len(file_proto_kvstore_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_kvstore_proto_goTypes,
		DependencyIndexes: file_proto_kvstore_proto_depIdxs,
		MessageInfos:      file_proto_kvstore_proto_msgTypes,
	}.Build()
	File_proto_kvstore_proto = out.File
	file_proto_kvstore_proto_goTypes = nil
	file_proto_kvstore_proto_depIdxs = nil
}
